### ISSUE TITLE
Compiled Output

### ISSUE THREAD

**Issue by captDaylight** [nanostores/react#10]
When I try to test my package I'm getting 
```
           Details:
       
           /node_modules/nanostores/index.js:1
           ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){export {
                                                                                             ^^^^^^
       
           SyntaxError: Unexpected token 'export'
       
           > 1 | import { action, computed } from 'nanostores';

```

I think the output should be compiled to avoid issues like this.

Related issue:
https://github.com/kulshekhar/ts-jest/issues/970#issuecomment-1197621866

**Comment by ai** [comment]
It is ESM dependency. You need to run it in browser or ESM project.

**Comment by aralroca** [comment]
Please compile with [Microbundle](https://github.com/developit/microbundle) for example, is so useful to load in projects as Next.js that support commonjs and also esm, you can support both. @ai I can do a PR

**Comment by aralroca** [comment]
Instead of 1kb (a lot), can be just 400B after compile with Microbundle

**Comment by ai** [comment]
Extra build step makes library maintaince harder, I am trying to avoid build step in my projects.

It is much better for debugging to have in `node_modules` exactly the same you have on Github.

**Comment by aralroca** [comment]
@ai I understand, but then it is more complicated to use your libraries in SSR

**Comment by ai** [comment]
I think it is better to put effort into fixing ESM issues in frameworks

**Comment by aralroca** [comment]
In my case, I have solved it with a dynamic import that only imports the library in the client and not in server side. 

However, for the the compilation step in your libraries will bring several improvements:

- More support: `esm`, `cjs`, `umd` instead of just `esm`.
- packages would be even tinier and with optimized code

**Comment by aralroca** [comment]
You can close the issue for me, it's clear because it's done this way and it's 100% respectable.

I imagine that we will have to fight for frameworks like Next.js to support ESM in the Node part, or move to frameworks like Fresh with Deno there is not that problem.

BTW;  it is a very good library.

**Comment by ai** [comment]
I think Next.js will have ESM support in next major
