### ISSUE TITLE
TypeScript - When using `useStore` I get this Type Error  `Overload 1 of 2, '(store: Store): any', gave the following error.`

### ISSUE THREAD

**Issue by dsomel21** [nanostores/react#11]
Hey! I really like Nanostores the related libraries! 

I am new to TypeScript and I don't know how to fix this message.

## Description

<img width="1287" alt="Screen Shot 2023-03-26 at 4 10 00 PM" src="https://user-images.githubusercontent.com/17516559/227801870-b63ce781-26a9-4927-9564-37603c35025b.png">

I have a file (which, I guess is my "store") that has all the states that I would like to share in different parts of my application.

> **`src/store/tukFootnoteStore.ts`**
```ts
import { atom } from "nanostores";
import { FootnoteContent } from "../types/cmsFootnoteType";
import { Tuk } from "../types/appTypes";

export type Atom<T> = {
  value: T;
  set: (value: T) => void;
};

export const isOpen: Atom<boolean> = atom(false);
export const originalPauriTuks: Atom<Tuk[] | null> = atom(null);
export const originalTuk: Atom<string | null> = atom(null);
export const bhaiVirSinghFootnote: Atom<string | null> = atom(null);
export const customFootnotes: Atom<FootnoteContent | null> = atom(null);
```

## The Problem

As you can see, anytime I do `useStore(someArg)`, it doesn't like `someArg`, because **it says that it expects a `store`.** 

## What I have tried

* I tried to see if there was some `type` which I could import from `nanostore/react` but I couldn't find any
* I looked at the example in the README and in the [Astro Docs](https://docs.astro.build/en/core-concepts/sharing-state/#using-atoms), but they seem to be using it the same way I use it. `useStore(someStateVariable)`.

**Comment by ai** [comment]
The problem is because you define your own `Atom` type instead of using `nanostores`’ types.

You need to replace custom `Atom` to `Atom` from `nanostores`:

```ts
export const isOpen = atom(false);
export const originalPauriTuks = atom<Tuk[] | null>(null);
```

**Comment by dsomel21** [comment]
Wow! Thank you! 😄 That's great :)
