### ISSUE TITLE
What versions of React is supported by this library?

### ISSUE THREAD

**Issue by MrHBS** [nanostores/react#14]
What versions of React is supported by this library?

**Comment by ai** [comment]
Since React 18 (we need built-in batching)

**Comment by ai** [comment]
What we can use instead?

**Comment by ai** [comment]
Is it directly in `react` package? Sure! Send PR.

**Comment by dartess** [comment]
@MrHBS You have a desire to do PR? I could do it. I would like to do it.

**Comment by ai** [comment]
Thanks. The fix was released in 0.6.
