### ISSUE TITLE
The hook useStore leads to parasitic calls of onStart/onStop listeners

### ISSUE THREAD

**Issue by dartess** [nanostores/react#17]
Demo with problem: https://codesandbox.io/s/cranky-hoover-d3jq8i?file=/src/App.js

In console: 
```
onStart 1
onStart 2
onStart 3
```

As i understand, this happens because during the call to `useStore`, [store.get](https://github.com/nanostores/react/blob/44c0961564323ed7a23dd0a0c069a88f0fd9fbf0/index.js#LL13C2-L13C2) is called, which in turn calls [store.listen](https://github.com/nanostores/nanostores/blob/6d55daeb7a8a8ee2bf5295a243aa5e576d3ba450/atom/index.js#L20).

It seems I was able to fix the problem in the next way:

```diff
--- a/index.js
+++ b/index.js
@@ -10,7 +10,7 @@ export function useStore(store, opts = {}) {
     [opts.keys, store]
   )
 
-  let get = store.get.bind(store)
+  let get = useCallback(() => store.value, [store]);
 
   return useSyncExternalStore(sub, get, get)
 }
```

Demo with fix: https://codesandbox.io/s/eloquent-leakey-ncj57t?file=/src/App.js

BUT - I'm not confident in the correctness of the solution, because at the type level, `value` is not a public API, and such a change could potentially break this package in the future.

Perhaps it would be beneficial to add a getter to the main library to retrieve the raw value without calling subscriptions? Something like `getRaw` or `getWithoutListenerNotify`? I'm having trouble with naming in this case.

Alternatively, another option is to add value to the types, thereby making it public. Currently, for example, there is lc in the types, which seems to be a service field, but nevertheless is present in the types. I don't like this option because it would likely require explaining to the user the difference between `value` and `get`.

Or maybe I'm overcomplicating things and could propose a PR with the current solution?

**Comment by ai** [comment]
The solution looks promising. Can you send PR?

**Comment by ai** [comment]
Sorry, I was on vacation.

Yes, we found the same problem. We are investigating your fix. It could take a day or two.

**Comment by ai** [comment]
Anyway, could you send PR to save your name in the project’s history.

**Comment by dartess** [comment]
@ai I came across such a solution in signals: https://github.com/preactjs/signals/blob/HEAD/README.md#signalpeek
the name of the method sounds reasonable. maybe we should add it to the core library first.

**Comment by ai** [comment]
The fix was released in 0.7

**Comment by dartess** [comment]
> Moving to .value broke computed. Store’s value can be passed to code only after onStart call.

I have an idea that `computed`s should not return `undefined` in `value`.
I didn't fully understand the sources, but it seems there is an option to override `value` for the computer atom, which will calculate the value before calling `onStart` (possibly using `value` dependent atoms). This would fix the types and the voiced issue. Or not?

> BTW, why do you use onStart/onStop instead of inMount?

There is no specific reason, I migrated from mobx and tried to keep the analogies. Mobx don't have subscription with cleanup, just two separate actions.

**Comment by ai** [comment]
`store.value` type is `Value | undefined`

I think we will revert the fix and highlight that `onStart`/`onStop` events are low-level and developers should use `onMount` in most cases (it has no problem with firing too often).

**Comment by dartess** [comment]
> store.value type is Value | undefined

In the message above, I suggested fixing this and doing `store.value` type is `Value`.

> it has no problem with firing too often

That's great if so. According to the documentation, I thought it was just sugar over `onStart`/`onStop` and that it won't make a difference.

**Comment by ai** [comment]
I fixed docs a little https://github.com/nanostores/nanostores/commit/5ace3f4bf401117f530b96b85e9c5e7d9c38d50a
